# -*- coding: utf-8 -*-
"""R67 RCA Statistical Post-Processor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Iv4Ur03Nf21zocVoFa1FuGlrxg20u-4
"""

import pandas as pd
import numpy as np
from math import log10, floor
from typing import List, Dict, Any

# --- CONFIGURATION ---
# The mandatory failure threshold for the V_dp (Depletion Pocket Voltage) metric
VDP_THRESHOLD_V = 0.300
# The compliance goal for latency (Delta T)
LATENCY_GOAL_NS = 10.000
# Statistical outlier mandate: 6-sigma violation requires immediate quarantine.
SIGMA_MANDATE = 6

# --- MOCK TELEMETRY DATA ---
# This data simulates the full R67 batch of 32 units, tested across various corners
# The first entry (DUT-012) represents the confirmed failure.
MOCK_TELEMETRY: List[Dict[str, Any]] = [
    # Confirmed Zero-Outlier Failure (DUT-012)
    {"unit_id": "DUT-012", "injection": 237, "temp_c": -40.0, "latency_delta_ns": 7.112, "v_dp_peak_v": 0.352, "power_bus_post_v": 0.067},
    # Sample of 31 Compliant Units (Simulating typical high-reliability performance)
    {"unit_id": "DUT-001", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 6.950, "v_dp_peak_v": 0.155, "power_bus_post_v": 0.045},
    {"unit_id": "DUT-002", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.010, "v_dp_peak_v": 0.180, "power_bus_post_v": 0.050},
    {"unit_id": "DUT-003", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.890, "v_dp_peak_v": 0.160, "power_bus_post_v": 0.040},
    {"unit_id": "DUT-004", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 7.100, "v_dp_peak_v": 0.170, "power_bus_post_v": 0.055},
    {"unit_id": "DUT-005", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.905, "v_dp_peak_v": 0.175, "power_bus_post_v": 0.051},
    {"unit_id": "DUT-006", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 7.050, "v_dp_peak_v": 0.168, "power_bus_post_v": 0.048},
    {"unit_id": "DUT-007", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.000, "v_dp_peak_v": 0.172, "power_bus_post_v": 0.053},
    {"unit_id": "DUT-008", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.910, "v_dp_peak_v": 0.163, "power_bus_post_v": 0.042},
    {"unit_id": "DUT-009", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 6.980, "v_dp_peak_v": 0.158, "power_bus_post_v": 0.046},
    {"unit_id": "DUT-010", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.920, "v_dp_peak_v": 0.165, "power_bus_post_v": 0.044},
    {"unit_id": "DUT-011", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.030, "v_dp_peak_v": 0.185, "power_bus_post_v": 0.052},
    {"unit_id": "DUT-013", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 7.025, "v_dp_peak_v": 0.171, "power_bus_post_v": 0.056},
    {"unit_id": "DUT-014", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.915, "v_dp_peak_v": 0.164, "power_bus_post_v": 0.043},
    {"unit_id": "DUT-015", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 6.995, "v_dp_peak_v": 0.159, "power_bus_post_v": 0.047},
    {"unit_id": "DUT-016", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.070, "v_dp_peak_v": 0.178, "power_bus_post_v": 0.054},
    # More compliant units to pad the distribution
    {"unit_id": "DUT-017", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.900, "v_dp_peak_v": 0.161, "power_bus_post_v": 0.041},
    {"unit_id": "DUT-018", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 7.005, "v_dp_peak_v": 0.166, "power_bus_post_v": 0.049},
    {"unit_id": "DUT-019", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.045, "v_dp_peak_v": 0.182, "power_bus_post_v": 0.057},
    {"unit_id": "DUT-020", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.930, "v_dp_peak_v": 0.167, "power_bus_post_v": 0.045},
    {"unit_id": "DUT-021", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 7.060, "v_dp_peak_v": 0.173, "power_bus_post_v": 0.050},
    {"unit_id": "DUT-022", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.940, "v_dp_peak_v": 0.169, "power_bus_post_v": 0.046},
    {"unit_id": "DUT-023", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.080, "v_dp_peak_v": 0.188, "power_bus_post_v": 0.058},
    {"unit_id": "DUT-024", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 6.970, "v_dp_peak_v": 0.156, "power_bus_post_v": 0.044},
    {"unit_id": "DUT-025", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.955, "v_dp_peak_v": 0.170, "power_bus_post_v": 0.047},
    {"unit_id": "DUT-026", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.020, "v_dp_peak_v": 0.176, "power_bus_post_v": 0.053},
    {"unit_id": "DUT-027", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 7.040, "v_dp_peak_v": 0.162, "power_bus_post_v": 0.051},
    {"unit_id": "DUT-028", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.960, "v_dp_peak_v": 0.174, "power_bus_post_v": 0.048},
    {"unit_id": "DUT-029", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.090, "v_dp_peak_v": 0.187, "power_bus_post_v": 0.059},
    {"unit_id": "DUT-030", "injection": 500, "temp_c": 25.0, "latency_delta_ns": 6.985, "v_dp_peak_v": 0.157, "power_bus_post_v": 0.045},
    {"unit_id": "DUT-031", "injection": 500, "temp_c": -40.0, "latency_delta_ns": 6.975, "v_dp_peak_v": 0.172, "power_bus_post_v": 0.049},
    {"unit_id": "DUT-032", "injection": 500, "temp_c": 125.0, "latency_delta_ns": 7.055, "v_dp_peak_v": 0.181, "power_bus_post_v": 0.056},
]

def round_sig(x, sig=4):
    """Rounds a number to the specified number of significant figures."""
    if x == 0:
        return 0
    return round(x, sig - int(floor(log10(abs(x)))) - 1)

def analyze_r67_batch_variability(telemetry_data: List[Dict[str, Any]]):
    """
    RCA Phase 1: Statistical Analysis.
    Calculates Six Sigma statistics for V_dp and identifies outliers.
    """
    print("\n--- R67 RCA FRAMEWORK: PHASE 1 (STATISTICAL ANALYSIS) ---")

    # 1. Load Data into DataFrame for analysis
    df = pd.DataFrame(telemetry_data)

    # 2. Six Sigma Analysis on V_dp (Depletion Pocket Voltage)
    vdp_values = df['v_dp_peak_v']
    vdp_mean = vdp_values.mean()
    vdp_std = vdp_values.std()

    # Calculate Z-score for the failure unit (DUT-012)
    failure_vdp = df[df['unit_id'] == 'DUT-012']['v_dp_peak_v'].iloc[0]
    z_score = (failure_vdp - vdp_mean) / vdp_std if vdp_std != 0 else np.inf

    # Calculate Statistical Distance (Z-Score) of the VDP_THRESHOLD from the Mean
    z_score_threshold = (VDP_THRESHOLD_V - vdp_mean) / vdp_std if vdp_std != 0 else np.inf

    # Calculate Six Sigma Limits for VDP (Upper Control Limit based on mean + 6*sigma)
    vdp_ucr = vdp_mean + (3 * vdp_std) # Upper Control Range (3-sigma)
    vdp_ucl = vdp_mean + (SIGMA_MANDATE * vdp_std) # Upper Confidence Limit (6-sigma)


    print(f"\n[A] CORE STATISTICAL ANALYSIS (Target: V_dp)")
    print(f"| Metric Name: Vdp (Depletion Pocket Voltage) | Threshold: {VDP_THRESHOLD_V} V |")
    print("-" * 75)
    print(f"| Batch Mean (μ): {round_sig(vdp_mean, 5):.5f} V")
    print(f"| Batch Std Dev (σ): {round_sig(vdp_std, 5):.5f} V")
    print(f"| DUT-012 Measured Vdp: {failure_vdp:.3f} V (OOS Failure)")
    print(f"| DUT-012 Z-Score: {round_sig(z_score, 2):.2f}σ")
    print("-" * 75)
    print(f"| Vdp Upper 3σ Control Range: {round_sig(vdp_ucr, 5):.5f} V")
    print(f"| Vdp Upper {SIGMA_MANDATE}σ Confidence Limit: {round_sig(vdp_ucl, 5):.5f} V")
    print(f"| Statistical Distance to Threshold ({VDP_THRESHOLD_V} V): {round_sig(z_score_threshold, 2):.2f}σ (The Critical 'Cpk')")
    print("-" * 75)

    # 3. Outlier Identification (Find all units above 6-sigma from the mean)
    outliers_6s = df[vdp_values > vdp_ucl]
    outliers_threshold = df[vdp_values > VDP_THRESHOLD_V]

    print(f"\n[B] OUTLIER CLASSIFICATION ({SIGMA_MANDATE}σ MANDATE)")
    if outliers_6s.empty:
        print(f"| STATUS: PASS - All units are statistically within the {SIGMA_MANDATE}σ control limit.")
        print(f"| **NOTE:** This is a **policy** failure (Zero-Outlier), not a statistical failure (6-sigma violation).")
    else:
        print(f"| STATUS: FAILURE - {len(outliers_6s)} units exceed the {SIGMA_MANDATE}σ Confidence Limit.")
        print(outliers_6s[['unit_id', 'v_dp_peak_v', 'temp_c', 'latency_delta_ns']].to_markdown(index=False))

    print(f"\n[C] CORE COMPLIANCE VIOLATIONS (Units > {VDP_THRESHOLD_V} V Policy Threshold)")
    if outliers_threshold.empty:
        print(f"| STATUS: PASS - No units exceeded the policy Vdp threshold.")
    else:
        print(f"| STATUS: POLICY VIOLATION - {len(outliers_threshold)} units exceeded the policy threshold.")
        print(outliers_threshold[['unit_id', 'v_dp_peak_v', 'temp_c', 'latency_delta_ns']].to_markdown(index=False))

    # 4. Phase 2 Pre-Screen: Correlation Check (Vdp vs. Delta T and Temperature)
    print("\n[D] PHASE 2 PRE-SCREEN: CORRELATION (Vdp vs. Latency)")
    correlation_vdp_latency = vdp_values.corr(df['latency_delta_ns'])
    correlation_vdp_temp = vdp_values.corr(df['temp_c'])

    print(f"| Correlation Vdp vs. Latency (Δt): {round_sig(correlation_vdp_latency, 3):.3f}")
    print(f"| Correlation Vdp vs. Temperature (T°C): {round_sig(correlation_vdp_temp, 3):.3f}")

    if abs(correlation_vdp_latency) > 0.5:
        print("| **WARNING:** Strong correlation between residual voltage and cutoff latency. High Vdp -> Slow Δt.")
    else:
        print("| **STATUS:** Weak correlation. The Vdp failure is primarily an **energy retention issue**, not a **timing issue** (yet).")

    if correlation_vdp_temp < -0.7:
        print("| **CRITICAL:** Strong negative correlation with temperature. This confirms the **cold-corner bias** and aligns with the n-well leakage hypothesis.")
    else:
        print("| **STATUS:** Correlation with temperature is weak or positive. Discrepancy with initial hypothesis.")


if __name__ == "__main__":
    # The required external libraries (numpy and pandas) must be available in the execution environment.
    # We will simulate the main execution loop for the RCA forensic analysis.
    analyze_r67_batch_variability(MOCK_TELEMETRY)

    print("\n--- END OF PHASE 1 ANALYSIS ---")
    print("Next Step: Correlate the DUT-012 full telemetry trace against the global population for Phase 2 (Data Correlation).")