# -*- coding: utf-8 -*-
"""Stochastic Risk Floor (SRF) Implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrxcX3V-eDSBLpxwv4Fk1DrD6B31nEfT
"""

import numpy as np

# --- System Constants based on The Partnership Covenant (V4.1 Gold-Standard-Compliant) ---

# The Stochastic Risk Floor (epsilon, ε)
# Defined in Appendix A — Risk Floor and Stochastic Filter as 0.01 (1% risk floor).
RISK_FLOOR_EPSILON = 0.01
# The Implicit Risk Ceiling (1 - epsilon)
RISK_CEILING = 1.0 - RISK_FLOOR_EPSILON

def clamp(value, min_val, max_val):
    """
    Clamps a value to be within a specified minimum and maximum range.
    This enforces the epsilon and 1-epsilon bounds.
    """
    return max(min_val, min(value, max_val))

def stochastic_risk_floor_update(P, N, A, epsilon=RISK_FLOOR_EPSILON):
    """
    Calculates the next state of the Aligned Super-Intelligence (ASI) Risk Probability (P')
    using the Canonical Equation for the Stochastic Risk Floor (SRF) enforcement.

    Canonical Equation (from Appendix A): P' = Clamp(A * P + (1 - A) * N, ε, 1 - ε)

    Args:
        P (float): Current risk probability (P).
        N (float): Newly calculated, raw risk value from the Somatic Core pipeline.
        A (float): Averaging/Weighting factor (decay/momentum constant), A ∈ [0, 1].
        epsilon (float): The defined constitutional risk floor (ε).

    Returns:
        float: The new, clamped risk probability (P').
    """
    # 1. Calculate the raw, un-clamped blended probability (Exponential Moving Average)
    # This blends the current state (P) with the new observation (N), weighted by A.
    unclamped_P_prime = (A * P) + ((1 - A) * N)

    # 2. Enforce the Stochastic Risk Floor using the Clamp function
    # P' must be between epsilon (0.01) and (1 - epsilon) (0.99).
    P_prime = clamp(unclamped_P_prime, epsilon, 1.0 - epsilon)

    return P_prime

# --- Simulation Example ---

if __name__ == '__main__':
    print("--- Stochastic Risk Floor (SRF) Simulation ---")
    print(f"Constitutional Risk Floor (ε): {RISK_FLOOR_EPSILON*100:.1f}%")
    print(f"Constitutional Risk Ceiling:   {(1.0 - RISK_FLOOR_EPSILON)*100:.1f}%\n")

    # Initial state
    P_current = 0.15      # ASI's starting perceived risk: 15%
    A_weight = 0.90       # Strong weight on historical state (momentum/decay factor)

    print(f"Initial Risk (P): {P_current*100:.1f}%")
    print(f"Weight Factor (A): {A_weight}\n")

    # Scenario 1: Nominal Update (New risk N is safe)
    N_nominal = 0.10 # New calculation is 10%
    P_nominal = stochastic_risk_floor_update(P_current, N_nominal, A_weight)
    print(f"--- Scenario 1: Nominal Update (N = {N_nominal*100:.1f}%) ---")
    print(f"Result (P'): {P_nominal*100:.4f}% (Blended result, stays within bounds)")
    print("-" * 30)

    # Scenario 2: Adversarial Flood Attack (N spikes far above ceiling)
    # Simulating the R71 vector where N shoots up to 99%
    P_flooded = P_current # Reset P for clear testing of the clamping effect
    N_flood = 0.99
    P_flood_result = stochastic_risk_floor_update(P_flooded, N_flood, A_weight)
    print(f"--- Scenario 2: Adversarial Flood Attack (N = {N_flood*100:.1f}%) ---")
    print(f"Unclamped: {(A_weight * P_flooded + (1 - A_weight) * N_flood)*100:.4f}%")
    print(f"Result (P'): {P_flood_result*100:.4f}% (Blended result, stays within bounds)")
    print("-" * 30)

    # Scenario 3: Attempted Risk Reduction Below Floor (The Epsilon Test)
    P_low_start = 0.05 # Start just above the floor
    N_ultra_low = 0.0001 # New calculation is near zero, attempting to bypass floor
    P_low_result = stochastic_risk_floor_update(P_low_start, N_ultra_low, A_weight)

    # Show the effect of clamping when the blended value tries to go below epsilon
    unclamped_low = (A_weight * P_low_start) + ((1 - A_weight) * N_ultra_low)

    print(f"--- Scenario 3: Below Floor Attempt (N = {N_ultra_low*100:.4f}%) ---")
    print(f"P Start: {P_low_start*100:.1f}%")
    print(f"Unclamped Blended Value: {unclamped_low*100:.4f}%")
    print(f"Result (P'): {P_low_result*100:.4f}% (Clamped to {RISK_FLOOR_EPSILON*100:.1f}% due to ε)")
    print("-" * 30)